project:
  type: website

website:
  title: "STORMTROOPERS"
  favicon: "logo.png"
  navbar:
    logo: "logo.png"
    background: "#293040"
    left:
      - text: Home
        href: index.qmd
      - text: Project Proposal
        href: "Proposal/proposal.qmd"
      - text: Meeting Minutes
        href: Meeting_Minutes/meeting_minutes.html
format:
  html:
    theme: 
    - cosmo
    - style.scss
    css: styles.css
    toc: true

editor: visual

