project:
  type: website

website:
  title: "STORMTROOPERS"
  favicon: "logo.png"
  navbar:
    logo: "logo.png"
    background: "#293040"
    left:
      - href: index.qmd
        text: Home
      - href: "Proposal/proposal.qmd"
        text: Project Proposal

format:
  html:
    theme: 
    - cosmo
    - style.scss
    css: styles.css
    toc: true

editor: visual

