project:
  type: website

website:
  title: "STORMTROOPERS"
  favicon: "logo.png"
  navbar:
    logo: "logo.png"
    background: "#293040"
    left:
      - text: Home
        href: index.html
      - text: Introduction
        href: introduction.html
      - text: Documentation
        menu: 
          - text: Project Proposal
            href: Proposal/proposal.html
          - text: Meeting Minutes
            href: Meeting_Minutes/meeting_minutes.html
      - text: Analysis
        menu: 
          - text: Data Preparation
            href: Analysis/Dataprep.html
          - text: Exploratory Data Analysis
            href: Analysis/EDA.html
          - text: Confirmatory Data Analysis
            href: Analysis/CDA.html
          - text: Forecasting
            href: Analysis/Forecasting.html
      - text: ShinyApp
        href: ShinyApp/ShinyApp.html

    right:
      - about.qmd
format:
  html:
    theme: 
    - cosmo
    toc: true

editor: visual

