project:
  type: website

website:
  title: "STORMTROOPERS"
  favicon: "logo.png"
  navbar:
    logo: "logo.png"
    background: "#293040"
    left:
      - text: Home
        href: index.qmd
      - text: Introduction
      - text: Project Documentation
        menu: 
          - text: Project Proposal
            href: "Proposal/proposal.qmd"
          - text: Meeting Minutes
            href: Meeting_Minutes/meeting_minutes.html
      - text: Analysis
        menu: 
          - text: Exploratory Data Analysis
            href: Analysis/EDA.html
          - text: Confirmatory Data Analysis
            href: Analysis/CDA.html
          - text: Forecasting
            href: Analysis/Forecasting.html
      - text: ShinyApp
        href: https://vaastormtroopers.shinyapps.io/VAAStormTroopers/

    right:
      - about.qmd
format:
  html:
    theme: 
    - cosmo
    toc: true

editor: visual

