project:
  type: website

website:
  title: "StormTroopers"
  favicon: "Logo.png"
  navbar:
    logo: "Logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: "Proposal/proposal.qmd"
        text: Project Proposal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

